spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:backend}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:senhadefault}
spring.datasource.driver-class-name=org.postgresql.Driver
app.security.jwt.secret=${JWT_SECRET:change-me-change-me-change-me-change-me}
